name: stac
description: Stac is a Server-Driven UI (SDUI) framework for Flutter. Stac allows you to build beautiful cross-platform applications with JSON in real time.
version: 1.0.0-dev.5
homepage: https://github.com/StacDev/stac

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

topics:
  - ui
  - widget
  - server-driven-ui
  - dynamic-widgets

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: 3.1.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  dio: ^5.8.0+1
  stac_framework: ^0.3.0
  cached_network_image:
    git:
      url: https://github.com/FareesHussain/flutter_cached_network_image.git
      ref: fix/gpu_allocation
      path: cached_network_image
  flutter_svg: 2.0.17
  stac_logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: 2.5.4
  freezed: 3.1.0
  json_serializable: 6.9.5